server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://101.200.81.211:3306/testls?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Abc123!_

social:
  qq:
    appId: 100550231
    appSecret: 69b6ab57b22f3c2fe6a6149274e3295e
    filterProcessesUrl: /qqLogin
    providerId: callback.do
    signupUrl: /signup
  weixin:
    appId: wxd99431bbff8305a0
    appSecret: 60f78681d063590a469f1b297feff3c4
